name: CI
on:
  push:
    branches:
    - main
  pull_request:
    types:
    - opened
    - synchronize

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: yarn
    - name: Lint
      run: yarn lint
      env:
        CI: true

  testIntegration:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: yarn
    - name: Build and link packages
      run: |
        yarn lerna bootstrap
        yarn lerna run --concurrency 1 build
        yarn lerna exec 'yarn link'
        yarn --silent lerna ls | xargs yarn link
    - name: Run tests
      run: yarn test --rootDir test/integration
      env:
        CI: true

  testScreenshots:
    - uses: actions/checkout@v1
    - name: Run tests
      run: |
        docker run --rm -v `pwd`:/app -w /app node /bin/bash ./run-screenshot-tests.sh
      env:
        CI: true

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: yarn
    - name: Build
      run: |
        yarn lerna bootstrap
        yarn lerna run --concurrency 1 build
      env:
        CI: true
